config/routes.rb
Weichuban::Application.routes.draw do
  resources :users do
    resources :books, :controller => 'books'
  end
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup', to: 'users#new'

  match '/about', to: 'static_pages#about'
  match '/wish', to: 'static_pages#wish'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

  root :to => 'static_pages#home'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :summary, :title
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 140 }
  validates :summary, length: { maximum: 2000 }
  validates :user_id, presence: true
  
  default_scope order: 'books.created_at DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :description, :alipay
  has_secure_password
  has_many :books, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { minimum: 2, maximum: 50 },
                   uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false },
                    length: { minimum: 3, maximum: 150 }
  validates :password, length: { minimum: 6, maximum: 80 }
  validates :password_confirmation, presence: true
  validates :description, length: { maximum: 800 }
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery 
  include SessionsHelper
  
  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/books_controller.rb
#encoding:UTF-8.
class BooksController < ApplicationController
  before_filter :find_user
  before_filter :signed_in_user, only: [:new, :edit, :create, :destroy, :update]
  #before_filter :correct_user,   only: [:new, :edit, :create, :destroy, :update]

  def new
    @book = current_user.books.build if signed_in?
  end
  
  def show
    @book = current_user.books.find( params[:id] )
  end
  
  def edit
    @book = current_user.books.find( params[:id] )
  end
  
  def destroy
  end
  
  def create
    @book = current_user.books.build(params[:book])
    if @book.save
      flash[:success] = "cool!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def update
    @book = current_user.books.find( params[:id] )
    if @book.update_attributes( params[:book] )
      flash[:success] = "您的书名已更新成功"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def index
    @books = @user.books
  end
  
  protected

  def find_user
    @user = User.find( params[:user_id] )
  end
  
end

app/controllers/sessions_controller.rb
#encoding:UTF-8.
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = '您输入的邮箱（Email）或密码不正确，请重新输入~'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def wish
  end
  
  def about
  end
end

app/controllers/users_controller.rb
#encoding:UTF-8.
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  
  def show
    @user = User.find(params[:id])
    @books = @user.books.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(params[:user])
     if @user.save
       sign_in @user
       redirect_to @user
     else
       render 'new'
    end
  end
  
  def edit
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "您的设置已更新成功"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private

  def signed_in_user
    redirect_to signin_url, notice: "请您新登录，谢谢~" unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
  
end

app/helpers/application_helper.rb
#encoding:UTF-8.
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "未出版"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
#encoding:UTF-8.
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "请您新登录，谢谢~"
    end
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/books/_book.html.erb
<li>
  <span class="title"><%= book.title %></span>
  <span class="title"><%= book.summary %></span>
  <span class="timestamp">
    <%= time_ago_in_words(book.created_at) %>前撰写
    <%= link_to '查看与继续写作', user_book_path(@user, book) %>
    <%= link_to '编辑书名与简介', edit_user_book_path(@user, book) %>
  </span>
</li>

app/views/books/_title_form.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title, "书名" %>
<%= f.text_field :title %>

<%= f.label :summary, "简介" %>
<%= f.text_field :summary %>

<%= f.submit "保存", class: "btn btn-success" %>

app/views/books/edit.html.erb
<% provide(:title, '编辑书名与简介') %>
<h2>编辑书名与简介</h2>

<div class="row">
  <div class="span5 offset3">
    <%= form_for @book, :url => user_book_path(@user, @book), :html => { :method => :put } do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title, "书名" %>
      <%= f.text_field :title %>

      <%= f.label :summary, "简介" %>
      <%= f.text_area :summary %>

      <%= f.submit "保存", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<% provide(:title, '写一本新书') %>
<h2>写一本新书</h2>

<div class="row">
  <div class="span5 offset3">
    <%= form_for @book, :url => user_books_path(@user) do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title, "书名" %>
      <%= f.text_field :title %>

      <%= f.label :summary, "简介" %>
      <%= f.text_field :summary %>

      <%= f.submit "保存", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
show

app/views/layouts/_footer.html.erb
<footer class="footer">
    <ul>
      <li><small><%= link_to "关于", about_path %></small></li>
      <li><small><%= link_to "愿景", wish_path %></small></li>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "未出版", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
        <li><%= link_to "首页", root_path, id: "login" %></li>
	 <li><%= link_to "作家榜", users_path, id: "login" %></li>
	 
        <% if signed_in? %>
	 
        <li><%= link_to current_user.name, current_user, id: "login" %></li>
	 <li><%= link_to "设置", edit_user_path(current_user), id: "login" %></li>
	 <li><%= link_to "退出", signout_path, method: "delete", id: "login" %></li>
	 
        <% else %>
        <li><%= link_to "登录", signin_path, id: "login" %></li>
        <li><%= link_to "注册", signup_path, id: "login" %></li>
        
        <% end %>
	 
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_book_form.html.erb
<li><%= link_to "新书...", new_user_book_path(current_user) %></li>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 50 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "我的作品", current_user %>
</span>
<span>
  <%= pluralize(current_user.books.count, "作品") %>
</span>

app/views/static_pages/about.html.erb
about

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/book_form' %>
      </section>
    </aside>
  </div>  
<% else %>
<div class="center hero-unit">
  <h1>未出版</h1>

  <h3>Hope is a good thing</h3>

  <%= link_to "注册",  signup_path, class: "btn btn-large btn-success" %>
</div>
<% end %> 

app/views/static_pages/wish.html.erb
wish

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, '个人设置') %>
<h2>个人设置</h2>

<div class="row">
  <div class="span5 offset3">
    <%= form_for(@user) do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "笔名" %>
      <%= f.text_field :name %>

      <%= f.label :email, "邮箱" %>
      <%= f.text_field :email %>
      
      <%= f.label :description, "我的简介" %>
      <%= f.text_field :description %>
      
      <%= f.label :alipay, "支付宝帐户（用于接受捐赠，请放心填写）" %>
      <%= f.text_field :alipay %>
      
      <%= f.label :password, "新密码" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "确认密码" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "保存", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

<h2></h2>

<div class="row">
  <div class="span5 offset3">
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">更改头像</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '作家榜') %>
<h2>作家榜</h2>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '注册') %>
<h2>注册</h2>

<div class="row">
  <div class="span5 offset3">
    <%= form_for(@user) do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "笔名" %>
      <%= f.text_field :name %>

      <%= f.label :email, "邮箱" %>
      <%= f.text_field :email %>

      <%= f.label :password, "密码" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "确认密码" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "创建帐号", class: "btn btn-large btn-success" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<div class="row">
  <aside class="span4">
    <section>
      <span class="title"><%= gravatar_for @user, size: 50 %></span>
      <span class="title"><%= @user.name %></span>
      <span class="title"><%= @user.description %></span>
    </section>
  </aside>
  <div class="span8">
    <% if @user.books.any? %>
      <h3>作品 (<%= @user.books.count %>)</h3>   
      <ol class="books">
        <%= render @books %>
      </ol>
      <%= will_paginate @books %>
    <% end %>
  </div>
</div>